### ISSUE TITLE
Remove commented code

### ISSUE THREAD

**Issue by probil** [liubich/TheRange#3]
Commented code is code smell. Just remove it

https://github.com/liubich/TheRange/blob/248e53b217391e6bc8658682de3b97c3b6f61a61/index.html#L10

https://github.com/liubich/TheRange/blob/248e53b217391e6bc8658682de3b97c3b6f61a61/index.html#L36

https://github.com/liubich/TheRange/blob/248e53b217391e6bc8658682de3b97c3b6f61a61/css/main.css#L22

**Comment by liubich** [comment]
@probil, I left this comments for future development. Is this so wrong?

**Comment by probil** [comment]
@liubich For this project it's not a big deal but in general it is.

Commented code in general:
1. Means something only for you, other team players will have no courage to remove it because they think that it is important (but it's not)
2. It becomes rotten quickly because people tend to update code but not comments
3. You can't predict the future so it will be in project forever
4. There are better places to store future work (other branch, gist, IDE history, whatever)
5. Increases cognitive load so it's harder to focus on real stuff

https://kentcdodds.com/blog/please-dont-commit-commented-out-code
Also consider reading "Clean Code" by Robert C. Martin at some point of your career :)

**Comment by liubich** [comment]
@probil, you've convinced me
